### ISSUE TITLE
Failure to Initialize Extension With No Errors

### ISSUE THREAD

**Issue by erixtekila** [leonardoventurini/meteor-devtools-evolved#2]
My project is working with Meteor devtool and Minimongo extensions, but not this one.
Any error message to track ?

I've disabled the other tools, but nothing happens also.

My stack is Meteor 1.9 + Grapher + Grapher react.

Thanks.
I was disappointing that such an useful tool wasn't keeping up-to-date.

**Comment by xpressabhi** [comment]
Nothing appears for me either.
Using Meteor 1.10.1 with Blaze

**Comment by leonardoventurini** [comment]
Hello @erixtekila and @xpressabhi did you get any errors in the console?

**Comment by leonardoventurini** [comment]
By the way, sorry for the delay, GitHub apparently didn't notify me. :confused: I will keep this in mind for now on. Thanks.

Now I remember I have run into something like this when there was an error happening before the extension was injected.

Anyhow, I did develop it using Meteor 1.9, it certainly shouldn't be anything to do with the version, but I will double-check.

**Comment by xpressabhi** [comment]
I don't see any relavant error in console. There are some warnings like this..

DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map

This seems to be adblocker warning or password autofill.

**Comment by erixtekila** [comment]
> did you get any errors in the console?

Nope, none.

**Comment by leonardoventurini** [comment]
@xpressabhi @erixtekila are you guys using the old DevTools at the same time, can you guys try to disable any other extension which might be interfering with it? If it works, I can try improving its compatibility.

**Comment by erixtekila** [comment]
Yes @leonardoventurini, I've run your devtool in isolation.
The panels appear, but no log in it.
Any way to debug it ?…

**Comment by leonardoventurini** [comment]
I will certainly try to replicate that locally as soon as possible. I would appreciate any additional info you can gather about the stack you are using.

You are also welcome to clone the repo and build the development version and try to debug or experiment with it. If the old devtools is working then theoretically mine should too since the injectors are very alike.

On a working instance of this extension normally there would be a log indicating how many attempts it had to take in order to detect Meteor and inject the decorators, for example:

![image](https://user-images.githubusercontent.com/17411182/77119760-7ea3bb00-6a0d-11ea-8fc4-51e3203d9f05.png)

Sometimes something will run before that happens and interfere with it especially if it is an exception, perhaps something is applying decorators to the same methods the extension is.

A quick note, you have to load the page with the DevTools open, so a simple refresh should solve it. I guess it was some mistake I made to have the injection depending on the devtools being loaded... I will try to fix that as soon as I can.

But it is likely that's not it in your case... I will have to investigate further.

**Comment by xpressabhi** [comment]
Installed it again and now it works. :)
I even see now Meteor DevTools Evolved: Initialized. (Attempts:3)

**Comment by xpressabhi** [comment]
I see this error 
Uncaught Error: Extension context invalidated.

**Comment by leonardoventurini** [comment]
> I see this error
> Uncaught Error: Extension context invalidated.

I think that is pretty normal and due to your reinstalling the extension, I also get that when I reload the extension for development and there is an instance running at the same time.

Thank you very much for reporting these issues, it is expected to there be issues as it is very early in its development, and I am going to do a bunch of fixes/improvements first before releasing again since every extension has to be reviewed for a few days before being approved by the Chrome Extension team.

**Comment by heticeric** [comment]
I've uninstalled then reinstalled, without any success.

I'll try the development one.
But Would you mind drive me on how to install it, while bundled.

**Comment by erixtekila** [comment]
OK, my version works only on local project.
Not deployed ones.

**Comment by leonardoventurini** [comment]
@heticeric I will definitely write a proper tutorial on contributing in the repo, for now, you only need to run `npm install` inside `devapp/` and at the root, then run `npm start` at the root. It will build the unpacked extension in the `chrome/` directory, which you can add to Chrome in development mode.

@erixtekila Can you provide me a public link to your deployed project? That would help a lot.

**Comment by chiefchef** [comment]
![Screenshot from 2020-03-20 16-52-12](https://user-images.githubusercontent.com/15325459/77209029-32b74b80-6acb-11ea-83a8-37d876a4feb6.png)
I get nothing...

**Comment by leonardoventurini** [comment]
@chiefchef thanks for the feedback, I will try to spare this weekend for investigating what is causing this and do some more optimizations. do you happen to have anything in your console?

**Comment by leonardoventurini** [comment]
I have added a fix to the development branch, you all are welcome to build and test locally. I will release as soon as I have all the requested features implemented and issues resolved. Thanks.

**Comment by leonardoventurini** [comment]
By the way, in the next release, the dev tools panel will not need to be loaded for it to be initialized anymore. :zap:

**Comment by aramix** [comment]
```
VM219 shell.js:171 Main._createAppUI: 42.17919921875ms
09:32:28.848 VM219 shell.js:171 Main._showAppUI: 25.72607421875ms
09:32:29.041 VM219 shell.js:171 Main._initializeTarget: 15.98388671875ms
09:32:29.198 ://devtools/bundled/persistence/IsolatedFileSystem.js:53 File system error: A requested file or directory could not be found at the time an operation was processed. when requesting entry ''
errorHandler @ ://devtools/bundled/persistence/IsolatedFileSystem.js:53
09:32:29.397 VM219 shell.js:171 Main._lateInitialization: 166.3349609375ms
09:32:40.278 bundle.js:2 Setting up bridge...
09:33:08.206 Navigated to devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@5f4eb224680e5d7dca88504586e9fd951840cac6/&can_dock=true&dockSide=undocked&experiments=true
```

**Comment by leonardoventurini** [comment]
@aramix looks like a chromium bug, which OS and Chrome version are you on?

**Comment by aramix** [comment]
macOS Catalina 10.15.3
Chrome 80.0.3987.149

**Comment by leonardoventurini** [comment]
@aramix thank you, I will investigate further for a fix or workaround.

**Comment by chiefchef** [comment]
@leonardoventurini It appears to be working now!

**Comment by leonardoventurini** [comment]
@chiefchef great! I didn't release yet... ¯\\\_(ツ)\_/¯ I did some adjustments to the initialization machinery and I will make many others more until the next release.

**Comment by pjbrow** [comment]
@leonardoventurini Just to add my voice to the chorus: I'm seeing the same problems with initialisation as well.  Blank canvas after John Travolta disappears.

Crome Version 80.0.3987.162 
macOS Catalina 10.15.3

I also tried it out on Chrome Canary Version 83.0.4101.0 (Official Build) canary (64-bit) - no joy there either.

**Comment by leonardoventurini** [comment]
hello @pjbrow thanks for the feedback, a new version of the extension is in review by the Chrome Team, I provided a fix for several issues among new features.
I discovered that for some reason lodash pollutes the global scope when building with Webpack and UMD parsing enabled, and doesn't play well when projects using old versions or even underscore.

It might take few more days for the new version to be available as Chrome announced slow reviews due to the virus.

It would be immensely helpful if you take a screenshot any console errors if there were any, as it might be something else entirely. You can even inspect the extension itself and check its console.

Thanks.

**Comment by pjbrow** [comment]
@leonardoventurini Thanks, really good of you to have run a new release.

There weren't any console errors I could see from the extension so I:

- went into the settings of the extension and hit the switch for "Collect errors" to "on";
- right clicked on the console and hit "inspect";
- hit "refresh" on the app page to see what would happen in the extension console,

and the subs and pubs flooded onto the interface.  

I went to Chrome Canary and hit refresh - that started working too.  Now I can't replicate the error.  Go figure.

**Comment by leonardoventurini** [comment]
Hehe sorry about that @pjbrow the messages are intended as a comic effect... btw, I changed a few things, now the extension initialises from the content script, not being necessary for the devtools panel to be open for that (only for receiving the logs). Hopefully Chrome finishes reviewing and releases the extension soon.

Thanks for using the extension, that was just the first release so it was kind of expected to there be some issues, thankfully it is not something more widespread - unless people are being very quiet about it hehe.

I intend on maintaining this extension for quite some time, so feel free to let me know any other issues you come against in the future.

**Comment by pjbrow** [comment]
@leonardoventurini Not at all.  I really appreciate this extension: it's golden for the app I work on.  Thanks for all your work!

**Comment by aramix** [comment]
1.1 works fine for me too. Thanks, looks awesome!

**Comment by leonardoventurini** [comment]
Chrome just released it! :tada: Let me know of any issues. Thanks.

**Comment by leonardoventurini** [comment]
Looks like it was solved.

**Comment by evolross** [comment]
I just installed the latest extension for the first time in Chrome and get a blank interface (i.e. no actual data in any of the tabs).

Chrome 100.0.4896.127
Meteor DevTools Evolved 1.5
